const BASE_HISCORES_URL = 'https://services.runescape.com/m=hiscore_oldschool';

const HISCORES_URLS = {
  main: BASE_HISCORES_URL,
  iron: `${BASE_HISCORES_URL}_ironman`,
  uim: `${BASE_HISCORES_URL}_ultimate`,
  hcim: `${BASE_HISCORES_URL}_hardcore_ironman`,
  dmm: `${BASE_HISCORES_URL}_deadman`,
  sdmm: `${BASE_HISCORES_URL}_seasonal`,
  dmmt: `${BASE_HISCORES_URL}_tournament`,
};

const GE_URLS = {
  detail:
    'http://services.runescape.com/m=itemdb_oldschool/api/catalogue/detail.json',
  graph: 'http://services.runescape.com/m=itemdb_oldschool/api/graph',
};

const STATS = {
  skills: [
    'overall',
    'attack',
    'defence',
    'strength',
    'hitpoints',
    'ranged',
    'prayer',
    'magic',
    'cooking',
    'woodcutting',
    'fletching',
    'fishing',
    'firemaking',
    'crafting',
    'smithing',
    'mining',
    'herblore',
    'agility',
    'thieving',
    'slayer',
    'farming',
    'runecraft',
    'hunter',
    'construction',
  ],
  bh: ['hunter', 'rogue'],
  lms: {},
  clues: ['all', 'beginner', 'easy', 'medium', 'hard', 'elite', 'master'],
  soulWarsZeal: {},
  bosses: [
    'Abyssal Sire',
    'Alchemical Hydra',
    'Barrows Chests',
    'Bryophyta',
    'Callisto',
    'Cerberus',
    'Chambers of Xeric',
    'Chambers of Xeric: Challenge Mode',
    'Chaos Elemental',
    'Chaos Fanatic',
    'Commander Zilyana',
    'Corporeal Beast',
    'Crazy Archaeologist',
    'Dagannoth Prime',
    'Dagannoth Rex',
    'Dagannoth Supreme',
    'Deranged Archaeologist',
    'General Graardor',
    'Giant Mole',
    'Grotesque Guardians',
    'Hespori',
    'Kalphite Queen',
    'King Black Dragon',
    'Kraken',
    "Kree'Arra",
    "K'ril Tsutsaroth",
    'Mimic',
    'Nex',
    'Nightmare',
    "Phosani's Nightmare",
    'Obor',
    'Sarachnis',
    'Scorpia',
    'Skotizo',
    'Tempoross',
    'The Gauntlet',
    'The Corrupted Gauntlet',
    'Theatre of Blood',
    'Theatre of Blood: Hard Mode',
    'Thermonuclear Smoke Devil',
    'TzKal-Zuk',
    'TzTok-Jad',
    'Venenatis',
    "Vet'ion",
    'Vorkath',
    'Wintertodt',
    'Zalcano',
    'Zulrah',
  ],
};

module.exports = {
  HISCORES_URLS,
  STATS,
  GE_URLS,
};
